# Name of your workflow.
name: dev channel test
# Trigger the workflow on push or pull request.
on: [pull_request]
# A workflow run is made up of one or more jobs.
jobs:
  prepare:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"
  test:
    strategy:
      matrix:
        config:
          - {name: ios-test, os: macOS-latest, build_options: "ios --release --no-codesign"}
          - {name: android-test, os: ubuntu-latest, build_options: "apk"}
    needs: prepare
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.17.x' # you can use 1.17
          channel: 'stable' # optional, default to: 'stable'
      - run: flutter doctor
      - run: flutter pub get
      - run: bin/lint.sh
      - run: flutter test
      - run: flutter build ${{ matrix.config.build_options }}